### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by sobolevn** [quantum-elixir/quantum-storage-persistent-ets#9] opened 2019-03-06 10:43 UTC
Hi! 

Thanks for building this tool. It would be awesome to have pure `elixir` persistent cron jobs.
But, this project looks abandoned. It might need some help.

What can I help you with to make it fully working and release it?

**Comment by maennchen** [comment] 2020-02-28 15:19
Sorry for the long wait. To get this library out, all issues tagged with milestone v1.0.0 have to be resolved.

Everyone is more than welcome to help this library. We can use help with

* Reproducing issues (Maybe write a failing test for bugs)
* Writing tests
* Writing Docs

I'm going to close this issue since all necessary thing are tracked in separate issues.

**Closed as completed by maennchen** 2020-02-28 15:20 UTC
Labels: question
